# Default values for demo2-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operatorNamespace: demo-o-ns
domainsNamespace: demo-d-ns
domainUID: demo2-domain-uid
domainLogsPersistentVolumeDir: /scratch/k8s-dir/demo2-domain-uid/domain-logs
weblogicImage: store/oracle/weblogic:12.2.1.3
weblogicImagePullPolicy: IfNotPresent
weblogicDomainCredentialsSecretName: demo2-domain-uid-domain-creds
extraEnv:
- name: PROPERTY1
  value: VALUE1

podTemplates:
  default: {}
  debug:
    extraEnv:
    - name: PROPERTY1
      value: VALUE1
    - name: PROPERTY2
      value: VALUE2
domainIntrospectors:
  default:
    podTemplate: podTemplate1
sitCfgGenerators:
  default:
    podTemplate: default
adminServerTemplates:
  default:
    podTemplate: default
  debug:
    podTemplate: debug
managedServerTemplates:
  default:
    podTemplate: default

extraVolumeMounts:
- name: weblogic-domain-home-storage-volume
  mountPath: /domain-home
extraVolumes:
- name: weblogic-domain-home-storage-volume
  persistentVolumeClaim:
    claimName: demo2-domain-uid-weblogic-domain-home-pvc
extraResources:
- kind: PersistentVolume
  apiVersion: v1
  metadata:
    labels:
      weblogic.domainUID: demo2-domain-uid
      weblogic.resourceVersion: domain-v1
    name: demo2-domain-uid-weblogic-domain-home-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: demo2-domain-uid-weblogic-domain-home-pvc
      namespace: demo-d-ns
    hostPath:
      path: /scratch/k8s-dir/demo2-domain-uid/domain-home
      type: ""
    persistentVolumeReclaimPolicy: Retain
    storageClassName: demo2-domain-uid-weblogic-domain-home-storage-class
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      weblogic.domainUID: demo2-domain-uid
      weblogic.resourceVersion: domain-v1
    name: demo2-domain-uid-weblogic-domain-home-pvc
    namespace: demo-d-ns
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: demo2-domain-uid-weblogic-domain-home-storage-class
    volumeName: demo2-domain-uid-weblogic-domain-home-pv

