kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-rolebinding
  namespace: {{ .Values.domainsNamespace }}
  labels:
    weblogic.resourceVersion: operator-v1
    weblogic.operatorName: {{ .Values.operatorNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operatorServiceAccount }}
  namespace: {{ .Values.operatorNamespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: weblogic-operator-namespace-role
  apiGroup: ""
