# Default values for demo4-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operatorNamespace: demo-o-ns
domainsNamespace: demo-d-ns
domainUID: demo4-domain-uid
domainLogsPersistentVolumeDir: /scratch/k8s-dir/demo4-domain-uid/domain-logs
podDomainHomeDir: /u01/oracle/domain-home
weblogicImage: wls-12213-domain-in-image:latest
weblogicImagePullPolicy: IfNotPresent
weblogicDomainCredentialsSecretName: demo4-domain-uid-domain-creds
extraEnv:
- name: PROPERTY1
  value: VALUE1

podTemplates:
  default: {}
  debug:
    extraEnv:
    - name: PROPERTY1
      value: VALUE1
    - name: PROPERTY2
      value: VALUE2
domainIntrospectors:
  default:
    podTemplate: default
sitCfgGenerators:
  default:
    podTemplate: default
adminServerPodTemplates:
  default:
    podTemplate: default
  debug:
    podTemplate: debug
managedServerPodTemplates:
  default:
    podTemplate: default
  debug:
    podTemplate: debug

adminServerServiceTemplates:
  default: {}
adminServerT3ServiceTemplates:
  default: {}
managedServerServiceTemplates:
  default: {}

#extraVolumeMounts:
#- name: weblogic-domain-home-storage-volume
#  mountPath: /domain-home
#extraVolumes:
#- name: weblogic-domain-home-storage-volume
#  persistentVolumeClaim:
#    claimName: demo4-domain-uid-weblogic-domain-home-pvc
#extraResources:
#- kind: PersistentVolume
#  apiVersion: v1
#  metadata:
#    labels:
#      weblogic.domainUID: demo4-domain-uid
#      weblogic.resourceVersion: domain-v1
#    name: demo4-domain-uid-weblogic-domain-home-pv
#  spec:
#    accessModes:
#    - ReadWriteMany
#    capacity:
#      storage: 5Gi
#    claimRef:
#      apiVersion: v1
#      kind: PersistentVolumeClaim
#      name: demo4-domain-uid-weblogic-domain-home-pvc
#      namespace: demo-d-ns
#    hostPath:
#      path: /scratch/k8s-dir/demo4-domain-uid/domain-home
#      type: ""
#    persistentVolumeReclaimPolicy: Retain
#    storageClassName: demo4-domain-uid-weblogic-domain-home-storage-class
#- kind: PersistentVolumeClaim
#  apiVersion: v1
#  metadata:
#    labels:
#      weblogic.domainUID: demo4-domain-uid
#      weblogic.resourceVersion: domain-v1
#    name: demo4-domain-uid-weblogic-domain-home-pvc
#    namespace: demo-d-ns
#  spec:
#    accessModes:
#    - ReadWriteMany
#    resources:
#      requests:
#        storage: 5Gi
#    storageClassName: demo4-domain-uid-weblogic-domain-home-storage-class
#    volumeName: demo4-domain-uid-weblogic-domain-home-pv
