apiVersion: v1
kind: Service
metadata:
  labels:
    weblogic.channelName: T3Channel
    weblogic.createdByOperator: "true"
    weblogic.domainName: poc-domain
    weblogic.domainUID: poc-duid
    weblogic.resourceVersion: domain-v1
    weblogic.serverName: as
  name: poc-duid-as-extchannel-t3channel
  namespace: poc-d-ns
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30212
    port: 30212
    protocol: TCP
    targetPort: 30212
  selector:
    weblogic.createdByOperator: "true"
    weblogic.domainUID: poc-duid
    weblogic.serverName: as
  type: NodePort
