# Default values for the weblogic operator.
setupKubernetesCluster: true
createOperator: true
createOperatorNamespace: true
operatorNamespace: weblogic-operator
operatorServiceAccount: weblogic-operator
createDomainsNamespace: true
domainsNamespaces: {}
operatorImage: weblogic-kubernetes-operator:1.0
operatorImagePullPolicy: IfNotPresent
#internalOperatorCert: ...
#internalOperatorKey: ...
externalRestEnabled: false
externalRestHttpsPort: 31001
#externalOperatorCert: ...
#externalOperatorKey: ...
remoteDebugNodePortEnabled: false
internalDebugHttpPort: 30999
externalDebugHttpPort: 30999
javaLoggingLevel: INFO
elkIntegrationEnabled: false
