# Copyright 2017, 2018, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.domainUid }}-weblogic-domain-pv
  labels:
    weblogic.domainUID: {{ .Values.domainUid }}
    weblogic.domainName: {{ .Values.domainName }}
spec:
  storageClassName: {{ .Values.domainUid }}-weblogic-domain-storage-class
  capacity:
    storage: {{ .Values.weblogicDomainStorageSize }}
  accessModes:
    - ReadWriteMany
  # Valid values are Retain, Delete or Recycle
  persistentVolumeReclaimPolicy: {{ .Values.weblogicDomainStorageReclaimPolicy }}
  {{- if ne .Values.weblogicDomainStorageType "NFS" }}
  hostPath:
  {{- end }}
  {{- if eq .Values.weblogicDomainStorageType "NFS" }}
  nfs:
    server: {{ .Values.weblogicDomainStorageNFSServer }}
  {{- end }}
    path: "{{ .Values.weblogicDomainStoragePath }}"
