{{- $values := .Values -}}
{{- range $key, $element := $values.managedServerServiceTemplates -}}
---
kind: ConfigMap
metadata:
  labels:
    weblogic.createdByOperator: "true"
    weblogic.operatorName: {{ $values.operatorNamespace }}
    weblogic.resourceVersion: domain-v1
  name: {{ $values.domainUID }}-{{ $key }}-managed-server-service-template-cm
  namespace: {{ $values.domainsNamespace }}
data:
  server-service.yaml: |-
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
      labels:
        weblogic.createdByOperator: "true"
        weblogic.domainUID: {{ $values.domainUID }}
        weblogic.resourceVersion: domain-v1
        weblogic.serverName: %SERVER_NAME%
      name: {{ $values.domainUID }}-%SERVER_NAME%
      namespace: {{ $values.domainsNamespace }}
    spec:
      ports:
      - port: %SERVER_PORT%
        protocol: TCP
        targetPort: %SERVER_PORT%
      publishNotReadyAddresses: true
      selector:
        weblogic.createdByOperator: "true"
        weblogic.domainUID: {{ $values.domainUID }}
        weblogic.serverName: %SERVER_NAME%
      type: ClusterIP
{{- end }}
